name := "cli-utils"
packages := "
btop
distrobox
fzf
just
neovim
ripgrep
strace
tmux
vim-X11
wl-clipboard
"
base_images := "
quay.io/fedora/fedora-coreos:next
quay.io/fedora-ostree-desktops/kinoite:41
quay.io/fedora-ostree-desktops/silverblue:41
"

import '../sysext.just'

all: default
